services:
  django_web:
    build: ./django-frontend
    container_name: django-container
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=host.docker.internal
    env_file:
      - .env
    volumes:
      - ./django-frontend:/app
    restart: always

  fastapi_server:
    build: ./backend
    container_name: fastapi-container
    command: python app.py
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    restart: always